name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@c95ed4e5715faf591d63ed44c926ea71fa2e1033
    with:
      security: true
      test: true
      runtime: nix
      test-command: "nix shell nixpkgs#bun -c bun test"
